# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lid.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlid.proto\x12\x03lid\".\n\nLIDRequest\x12\x0b\n\x03pcm\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\".\n\x0bLIDResponse\x12\x10\n\x08language\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x32\x32\n\x03LID\x12+\n\x06\x44\x65tect\x12\x0f.lid.LIDRequest\x1a\x10.lid.LIDResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIDREQUEST']._serialized_start=18
  _globals['_LIDREQUEST']._serialized_end=64
  _globals['_LIDRESPONSE']._serialized_start=66
  _globals['_LIDRESPONSE']._serialized_end=112
  _globals['_LID']._serialized_start=114
  _globals['_LID']._serialized_end=164
# @@protoc_insertion_point(module_scope)
