# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: compress.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'compress.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ompress.proto\x12\x08\x63ompress\"\x13\n\x03PCM\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x14\n\x04Opus\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\x35\n\x08\x43ompress\x12)\n\x06\x45ncode\x12\r.compress.PCM\x1a\x0e.compress.Opus\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compress_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PCM']._serialized_start=28
  _globals['_PCM']._serialized_end=47
  _globals['_OPUS']._serialized_start=49
  _globals['_OPUS']._serialized_end=69
  _globals['_COMPRESS']._serialized_start=71
  _globals['_COMPRESS']._serialized_end=124
# @@protoc_insertion_point(module_scope)
