# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vad.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vad.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tvad.proto\x12\x03vad\"-\n\x05Start\x12\x0f\n\x07\x66low_id\x18\x01 \x01(\t\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\"\x13\n\x03Pcm\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x07\n\x05\x46lush\"g\n\x0b\x43lientFrame\x12\x1b\n\x05start\x18\x01 \x01(\x0b\x32\n.vad.StartH\x00\x12\x17\n\x03pcm\x18\x02 \x01(\x0b\x32\x08.vad.PcmH\x00\x12\x1b\n\x05\x66lush\x18\x03 \x01(\x0b\x32\n.vad.FlushH\x00\x42\x05\n\x03msg\"$\n\x0bServerFrame\x12\x15\n\x03pcm\x18\x01 \x01(\x0b\x32\x08.vad.Pcm2A\n\rVoiceActivity\x12\x30\n\x06Stream\x12\x10.vad.ClientFrame\x1a\x10.vad.ServerFrame(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vad_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_START']._serialized_start=18
  _globals['_START']._serialized_end=63
  _globals['_PCM']._serialized_start=65
  _globals['_PCM']._serialized_end=84
  _globals['_FLUSH']._serialized_start=86
  _globals['_FLUSH']._serialized_end=93
  _globals['_CLIENTFRAME']._serialized_start=95
  _globals['_CLIENTFRAME']._serialized_end=198
  _globals['_SERVERFRAME']._serialized_start=200
  _globals['_SERVERFRAME']._serialized_end=236
  _globals['_VOICEACTIVITY']._serialized_start=238
  _globals['_VOICEACTIVITY']._serialized_end=303
# @@protoc_insertion_point(module_scope)
